export const SET_BOOKS = "SET_BOOKS";
export const SET_BOOK_FORM_DATA = "SET_BOOK_FORM_DATA";
export const SET_BOOK_FORM_ERRORS = "SET_BOOK_FORM_ERRORS";

export const UPDATE_BOOK = "UPDATE_BOOK";
export const DELETE_BOOK = "DELETE_BOOK";

export const BOOK_REQUEST = "BOOK_REQUEST";
export const BOOK_FAILURE = "BOOK_FAILURE";
export const BOOK_SUCCESS = "BOOK_SUCCESS";

export const SET_AUTHORS = "SET_AUTHORS";
export const SET_AUTHOR_FORM_DATA = "SET_AUTHOR_FORM_DATA";
export const SET_AUTHOR_FORM_ERRORS = "SET_AUTHOR_FORM_ERRORS";

export const UPDATE_AUTHOR = "UPDATE_AUTHOR";
export const DELETE_AUTHOR = "DELETE_AUTHOR";

export const AUTHOR_REQUEST = "AUTHOR_REQUEST";
export const AUTHOR_FAILURE = "AUTHOR_FAILURE";
export const AUTHOR_SUCCESS = "AUTHOR_SUCCESS";

export const SET_GENRES = "SET_GENRES";
export const SET_SELECTED_GENRE = "SET_SELECTED_GENRE";

export const GENRE_REQUEST = "GENRE_REQUEST";
export const GENRE_FAILURE = "GENRE_FAILURE";
export const GENRE_SUCCESS = "GENRE_SUCCESS";

export const SET_SORT_COLUMN = "SET_SORT_COLUMN";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
