export const SET_BOOKS = "SET_BOOKS";
export const SET_BOOK_FORM_DATA = "SET_BOOK_FORM_DATA";
export const SET_BOOK_FORM_ERRORS = "SET_BOOK_FORM_ERRORS";

export const UPDATE_BOOK = "UPDATE_BOOK";
export const DELETE_BOOK = "DELETE_BOOK";

export const SAVE_BOOK_REQUEST = "SAVE_BOOK_REQUEST";
export const SAVE_BOOK_FAILURE = "SAVE_BOOK_FAILURE";
export const SAVE_BOOK_SUCCESS = "SAVE_BOOK_SUCCESS";

export const SET_AUTHORS = "SET_AUTHORS";
export const SET_AUTHOR_FORM_DATA = "SET_AUTHOR_FORM_DATA";
export const SET_AUTHOR_FORM_ERRORS = "SET_AUTHOR_FORM_ERRORS";

export const UPDATE_AUTHOR = "UPDATE_AUTHOR";
export const DELETE_AUTHOR = "DELETE_AUTHOR";

export const SAVE_AUTHOR_REQUEST = "SAVE_AUTHOR_REQUEST";
export const SAVE_AUTHOR_FAILURE = "SAVE_AUTHOR_FAILURE";
export const SAVE_AUTHOR_SUCCESS = "SAVE_AUTHOR_SUCCESS";

export const SET_GENRES = "SET_GENRES";
export const SET_SELECTED_GENRE = "SET_SELECTED_GENRE";

export const SET_SORT_COLUMN = "SET_SORT_COLUMN";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
